#!/usr/bin/env node
/**
 * End-to-end acceptance script for the V1 platform.
 *
 * It drives a running Worker over real HTTP (cookies, CSRF headers, JSON) and
 * exercises four flows:
 *
 *   1. ADMIN      — create a 40-question Reading test, validate, publish, preview
 *   2. TEACHER    — classroom, enrolment, assignment, reports, cross-classroom IDOR check
 *   3. STUDENT    — assignment attempt, autosave, integrity events, submit, marked result
 *   4. FULL MOCK  — multi-component sequence, section advance, submit
 *
 * Usage:
 *   npm run dev                     # in one terminal (Worker on :8787)
 *   npm run test:integration        # in another
 *
 * Environment:
 *   BASE_URL        default http://127.0.0.1:8787
 *   ADMIN_EMAIL     optional: log in as an existing admin instead of bootstrapping
 *   ADMIN_PASSWORD  required when ADMIN_EMAIL is set
 *
 * The script only talks to the public API: it never touches D1 directly.
 */
import process from 'node:process';

const BASE_URL = (process.env.BASE_URL ?? 'http://127.0.0.1:8787').replace(/\/$/, '');
const RUN = Date.now().toString(36);
const PASSWORD = 'Integration-Passw0rd!23';

let passed = 0;
let failed = 0;
const failures = [];

function assert(condition, message) {
  if (condition) {
    passed += 1;
    console.log(`    ✓ ${message}`);
  } else {
    failed += 1;
    failures.push(message);
    console.error(`    ✗ ${message}`);
  }
}

function section(title) {
  console.log(`\n${title}`);
}

/** Minimal cookie-jar HTTP client: one instance per signed-in identity. */
function createClient(label) {
  const cookies = new Map();
  let csrfToken = null;

  async function request(method, path, body, options = {}) {
    const headers = new Headers();
    if (cookies.size > 0) {
      headers.set('cookie', [...cookies.entries()].map(([name, value]) => `${name}=${value}`).join('; '));
    }
    headers.set('origin', BASE_URL);
    if (csrfToken && method !== 'GET' && method !== 'HEAD') headers.set('x-csrf-token', csrfToken);

    let payload;
    if (body instanceof FormData) {
      payload = body;
    } else if (body !== undefined) {
      headers.set('content-type', 'application/json');
      payload = JSON.stringify(body);
    }

    const response = await fetch(`${BASE_URL}${path}`, { method, headers, body: payload, redirect: 'manual' });

    const setCookie = response.headers.getSetCookie?.() ?? [];
    for (const cookie of setCookie) {
      const [pair] = cookie.split(';');
      const index = pair.indexOf('=');
      const name = pair.slice(0, index);
      const value = pair.slice(index + 1);
      if (value === '' ) cookies.delete(name);
      else cookies.set(name, value);
    }

    const text = await response.text();
    let json = null;
    if (text) {
      try {
        json = JSON.parse(text);
      } catch {
        json = null;
      }
    }

    if (!options.expectStatuses?.includes(response.status) && !response.ok) {
      throw new Error(`${label} ${method} ${path} -> ${response.status} ${text.slice(0, 300)}`);
    }

    return { status: response.status, body: json, text };
  }

  return {
    label,
    get: (path, options) => request('GET', path, undefined, options),
    post: (path, body, options) => request('POST', path, body ?? {}, options),
    put: (path, body, options) => request('PUT', path, body ?? {}, options),
    patch: (path, body, options) => request('PATCH', path, body ?? {}, options),
    delete: (path, options) => request('DELETE', path, undefined, options),
    setCsrfToken(token) {
      csrfToken = token;
    },
    async register(email, displayName, bootstrapAdmin = false) {
      const result = await request('POST', '/api/auth/register', { email, password: PASSWORD, displayName, bootstrapAdmin });
      csrfToken = result.body?.csrfToken ?? null;
      return result.body?.user;
    },
    async login(email) {
      const result = await request('POST', '/api/auth/login', { email, password: PASSWORD });
      csrfToken = result.body?.csrfToken ?? null;
      return result.body?.user;
    },
  };
}

// ---------------------------------------------------------------------------
// Test content generated by this script (original, answer-free in the browser)
// ---------------------------------------------------------------------------
const CANARY = `CANARY-${RUN}-DO-NOT-LEAK`;

function buildReadingContent({ profileId, suffix }) {
  const groups = [];
  // `answers` holds server-only answer keys, `responses` the candidate replies
  // this script submits (the shapes differ: keys carry accepted alternatives).
  const answers = new Map();
  const responses = new Map();
  let number = 1;
  let questionId = 0;

  const nextId = () => `q_${suffix}_${(questionId += 1)}`;

  // 1-10 True / False / Not Given
  const tfngValues = ['TRUE', 'FALSE', 'NOT_GIVEN'];
  const tfngQuestions = [];
  for (let index = 0; index < 10; index += 1) {
    tfngQuestions.push({
      id: nextId(),
      number,
      prompt: `Statement ${number}: paragraph ${String.fromCharCode(65 + (index % 6))} describes study method ${index + 1}.`,
      options: [],
      config: {},
    });
    const value = tfngValues[index % 3];
    answers.set(number, {
      kind: 'CHOICE',
      values: [value],
      evidence: `${CANARY}: server-only marking evidence for question ${number}.`,
    });
    responses.set(number, { value });
    number += 1;
  }
  groups.push({
    type: 'TRUE_FALSE_NOT_GIVEN',
    instructions: 'Write TRUE, FALSE or NOT GIVEN.',
    sharedOptions: [],
    config: {},
    rangeFrom: 1,
    rangeTo: 10,
    questions: tfngQuestions,
  });

  // 11-20 multiple choice (single)
  const mcqQuestions = [];
  for (let index = 0; index < 10; index += 1) {
    const options = [
      { id: 'A', text: `Option A for ${number}` },
      { id: 'B', text: `Option B for ${number}` },
      { id: 'C', text: `Option C for ${number}` },
      { id: 'D', text: `Option D for ${number}` },
    ];
    const correct = ['A', 'B', 'C', 'D'][index % 4];
    mcqQuestions.push({ id: nextId(), number, prompt: `Choose the correct option for question ${number}.`, options, config: {} });
    answers.set(number, { kind: 'CHOICE', values: [correct] });
    responses.set(number, { value: correct });
    number += 1;
  }
  groups.push({
    type: 'MCQ_SINGLE',
    instructions: 'Choose the correct letter A, B, C or D.',
    sharedOptions: [],
    config: {},
    rangeFrom: 11,
    rangeTo: 20,
    questions: mcqQuestions,
  });

  // 21-30 short answer (text)
  const shortQuestions = [];
  for (let index = 0; index < 10; index += 1) {
    const word = `answer${index + 1}`;
    shortQuestions.push({
      id: nextId(),
      number,
      prompt: `Write one word for question ${number}.`,
      options: [],
      config: {},
    });
    answers.set(number, { kind: 'TEXT', accept: [word] });
    responses.set(number, { value: word });
    number += 1;
  }
  groups.push({
    type: 'SHORT_ANSWER',
    instructions: 'Write no more than one word for each answer.',
    sharedOptions: [],
    config: { wordLimit: { max: 1 } },
    rangeFrom: 21,
    rangeTo: 30,
    questions: shortQuestions,
  });

  // 31-40 sentence completion (text)
  const completionQuestions = [];
  for (let index = 0; index < 10; index += 1) {
    const word = `complete${index + 1}`;
    completionQuestions.push({
      id: nextId(),
      number,
      prompt: `Complete the sentence for question ${number}: the study group met each [[${number}]].`,
      options: [],
      config: {},
    });
    answers.set(number, { kind: 'TEXT', accept: [word] });
    responses.set(number, { value: word });
    number += 1;
  }
  groups.push({
    type: 'SENTENCE_COMPLETION',
    instructions: 'Complete the sentences with one word.',
    sharedOptions: [],
    config: { wordLimit: { max: 1 } },
    rangeFrom: 31,
    rangeTo: 40,
    questions: completionQuestions,
  });

  // Attach the server-only answer material to each question. The worker stores
  // `answerKey`/`evidence`/`explanation` in `answer_keys` and never returns them
  // to a candidate payload (asserted below).
  for (const group of groups) {
    for (const question of group.questions) {
      const key = answers.get(question.number);
      question.answerKey = { kind: key.kind, ...(key.values ? { values: key.values } : {}), ...(key.accept ? { accept: key.accept } : {}) };
      question.evidence = key.evidence ?? null;
    }
  }

  const content = {
    sections: [
      {
        skill: 'READING',
        title: `Integration Reading Passage ${suffix}`,
        subtitle: 'Generated by scripts/integration.mjs',
        instructions: 'Read the passage and answer questions 1 to 40.',
        durationSeconds: 1800,
        passage: {
          title: `Integration Passage ${suffix}`,
          subtitle: null,
          paragraphs: [
            { label: 'A', text: 'Paragraph A of the integration fixture. It exists only to give the questions context.' },
            { label: 'B', text: 'Paragraph B describes a method, a cause and a consequence in plain language.' },
            { label: 'C', text: 'Paragraph C offers a qualification to the claim made in paragraph B.' },
            { label: 'D', text: 'Paragraph D compares two approaches without recommending either.' },
            { label: 'E', text: 'Paragraph E discusses cost, staffing and scheduling.' },
            { label: 'F', text: 'Paragraph F summarises the argument.' },
          ],
        },
        audioAssetId: null,
        playback: {},
        groups,
      },
    ],
    durationSeconds: 1800,
    isCompleteTest: true,
    scoringProfileId: profileId,
  };

  return { content, answers, responses };
}

function buildWritingContent() {
  return {
    sections: [
      {
        skill: 'WRITING',
        title: 'Writing Tasks',
        subtitle: null,
        instructions: 'Complete both tasks.',
        durationSeconds: 3600,
        passage: null,
        audioAssetId: null,
        playback: {},
        groups: [
          {
            type: 'WRITING_TASK_1',
            instructions: 'Write at least 150 words.',
            sharedOptions: [],
            config: { note: `Task 1 (${RUN})` },
            rangeFrom: 1,
            rangeTo: 1,
            questions: [
              {
                number: 1,
                prompt: 'Describe the chart. Write at least 150 words.',
                options: [],
                config: { wordLimit: { min: 150 } },
                answerKey: { kind: 'MANUAL' },
              },
            ],
          },
          {
            type: 'WRITING_TASK_2',
            instructions: 'Write at least 250 words.',
            sharedOptions: [],
            config: { note: `Task 2 (${RUN})` },
            rangeFrom: 2,
            rangeTo: 2,
            questions: [
              {
                number: 2,
                prompt: 'Discuss both views and give your opinion. Write at least 250 words.',
                options: [],
                config: { wordLimit: { min: 250 } },
                answerKey: { kind: 'MANUAL' },
              },
            ],
          },
        ],
      },
    ],
    durationSeconds: 3600,
    isCompleteTest: false,
  };
}

function candidateShapeContainsCanary(payload) {
  return JSON.stringify(payload).includes('CANARY-');
}

// ---------------------------------------------------------------------------
// Flows
// ---------------------------------------------------------------------------
async function adminFlow(admin) {
  section('Flow 1 — ADMIN: content pipeline (create → validate → publish → preview)');

  const profile = await admin.post('/api/admin/scoring-profiles', {
    name: `Integration Reading table ${RUN}`,
    skill: 'READING',
    testType: 'READING',
    minQuestions: 40,
    sourceNotes: 'Created by scripts/integration.mjs',
    ranges: [
      { rawMin: 0, rawMax: 9, band: 4 },
      { rawMin: 10, rawMax: 19, band: 5 },
      { rawMin: 20, rawMax: 29, band: 6 },
      { rawMin: 30, rawMax: 39, band: 7 },
      { rawMin: 40, rawMax: 40, band: 8 },
    ],
    activate: true,
  });
  assert(profile.status === 201 && profile.body.profileId, 'admin created a versioned scoring profile');

  const created = await admin.post('/api/admin/tests', {
    title: `Integration Reading ${RUN}`,
    type: 'READING',
    summary: 'Created by the acceptance script.',
    contentOrigin: 'ORIGINAL',
    sourceTitle: 'Generated fixture',
    attribution: 'Arena integration script',
    licenseNotes: 'Original generated content.',
  });
  assert(created.status === 201 && created.body.testId, 'admin created a draft test');

  const { content, answers, responses } = buildReadingContent({ profileId: profile.body.profileId, suffix: RUN });

  const saved = await admin.put(`/api/admin/versions/${created.body.versionId}/content`, content);
  assert(saved.body.totalQuestions === 40, 'content saved with 40 server-counted questions');
  assert(saved.body.validation.publishable === true, 'deterministic validation found no blocking errors');

  const published = await admin.post(`/api/admin/versions/${created.body.versionId}/publish`, {
    changeNote: 'Integration publish',
  });
  assert(published.status === 200 && published.body.ok === true, 'version published immutably');

  const republish = await admin.post(
    `/api/admin/versions/${created.body.versionId}/publish`,
    {},
    { expectStatuses: [409, 400] },
  );
  assert(republish.status >= 400, 're-publishing the same version is refused');

  const edit = await admin.put(
    `/api/admin/versions/${created.body.versionId}/content`,
    content,
    { expectStatuses: [409] },
  );
  assert(edit.status === 409, 'published content is immutable (editing requires a new version)');

  const catalog = await admin.get('/api/tests');
  assert(
    catalog.body.tests.some((test) => test.id === created.body.testId),
    'published test appears in the candidate catalogue',
  );

  const preview = await admin.get(`/api/admin/versions/${created.body.versionId}/preview`);
  const previewText = JSON.stringify(preview.body);
  assert(!previewText.includes('answerKey'), 'preview payload contains no answer-key field');
  assert(previewText.includes('Integration Passage'), 'preview payload contains the candidate-visible passage');
  assert(!candidateShapeContainsCanary(preview.body), 'preview payload exposes no marking evidence field');

  // A second, tiny writing test is needed as a full-mock component.
  const writingCreated = await admin.post('/api/admin/tests', {
    title: `Integration Writing ${RUN}`,
    type: 'WRITING',
    summary: 'Writing component for the full mock.',
    contentOrigin: 'ORIGINAL',
  });
  const writingContent = buildWritingContent();
  await admin.put(`/api/admin/versions/${writingCreated.body.versionId}/content`, writingContent);
  const writingPublished = await admin.post(`/api/admin/versions/${writingCreated.body.versionId}/publish`, {});
  assert(writingPublished.status === 200, 'writing version published for use as a mock component');

  return {
    testId: created.body.testId,
    versionId: created.body.versionId,
    writingVersionId: writingCreated.body.versionId,
    answers,
    responses,
  };
}

async function teacherFlow(admin, teacher, studentEmail) {
  section('Flow 2 — TEACHER: classroom, enrolment, assignment, reports, authorisation');

  const classroom = await teacher.post('/api/teacher/classrooms', {
    name: `Integration Class ${RUN}`,
    description: 'Created by the acceptance script.',
  });
  assert(classroom.status === 201 && classroom.body.classroom.id, 'teacher created a classroom');
  const classroomId = classroom.body.classroom.id;

  const invite = await teacher.post(`/api/teacher/classrooms/${classroomId}/invites`, {
    email: studentEmail,
    ttlHours: 24,
  });
  assert(invite.status === 201 && invite.body.shareUrl.includes('/join?token='), 'single-use invitation link generated');

  const enrolled = await teacher.post(`/api/teacher/classrooms/${classroomId}/members`, { email: studentEmail });
  assert(enrolled.status === 201, 'student enrolled by email');

  const detail = await teacher.get(`/api/teacher/classrooms/${classroomId}`);
  assert(detail.body.members.some((member) => member.email === studentEmail), 'member list includes the student');

  // A second teacher must not be able to read the first teacher's classroom.
  const intruder = createClient('intruder-teacher');
  const email = `intruder-${RUN}@example.test`;
  await admin.post('/api/admin/users', { email, displayName: 'Intruder Teacher', role: 'TEACHER', password: PASSWORD });
  await intruder.login(email);
  const forbidden = await intruder.get(`/api/teacher/classrooms/${classroomId}`, { expectStatuses: [403, 404] });
  assert(forbidden.status === 403 || forbidden.status === 404, 'another teacher cannot read the classroom (IDOR blocked)');

  return { classroomId, intruder };
}

async function assignmentFlow(teacher, { classroomId, versionId }) {
  const deadline = new Date(Date.now() + 7 * 24 * 3_600_000).toISOString();
  const assignment = await teacher.post('/api/teacher/assignments', {
    classroomId,
    testVersionId: versionId,
    title: `Integration Assignment ${RUN}`,
    deadlineAt: deadline,
    maxAttempts: 2,
    mode: 'STANDARD_EXAM',
    resultVisibility: 'IMMEDIATE',
    timingPolicy: 'EXAM_DURATION',
    integrityOverrides: { maxTabAwayEvents: 3, warnAtEvents: 1 },
    publish: true,
  });
  assert(assignment.status === 201 && assignment.body.assignmentId, 'assignment created for the published version');

  const detail = await teacher.get(`/api/teacher/assignments/${assignment.body.assignmentId}`);
  assert(detail.body.report.length >= 1, 'assignment report lists the enrolled students');
  return assignment.body.assignmentId;
}

async function studentFlow(student, { assignmentId, responses, testId }) {
  section('Flow 3 — STUDENT: attempt, autosave, integrity, submit, marked result');

  const dashboard = await student.get('/api/student/dashboard');
  assert(dashboard.status === 200 && Array.isArray(dashboard.body.assignments), 'student dashboard loads with assignments');

  const started = await student.post('/api/attempts', { assignmentId, clientMeta: { timezone: 'UTC' } });
  assert(started.status === 201 && started.body.attemptId, 'attempt started from an assignment');
  const attemptId = started.body.attemptId;

  const state = await student.get(`/api/attempts/${attemptId}`);
  assert(state.status === 200 && state.body.content.sections.length === 1, 'candidate attempt state returns the section');
  const candidateText = JSON.stringify(state.body);
  assert(!candidateText.includes('answerKey'), 'candidate payload contains no answer keys');
  assert(!candidateText.includes(CANARY), 'candidate payload contains no server-only evidence text');
  assert(typeof state.body.time.serverNow === 'string', 'server time is authoritative in the payload');

  const questions = state.body.content.sections[0].groups.flatMap((group) => group.questions);
  assert(questions.length === 40, 'all 40 questions are visible to the candidate');

  // Answer 30 of 40 correctly: the profile maps 30-39 to band 7.0.
  const updates = questions.slice(0, 30).map((question) => ({
    questionId: question.id,
    response: responses.get(question.number),
  }));
  const autosave = await student.patch(`/api/attempts/${attemptId}/answers`, { updates });
  assert(autosave.status === 200 && autosave.body.ok === true, 'answers autosaved through the batch endpoint');

  const integrity = await student.post(`/api/attempts/${attemptId}/integrity`, {
    events: [
      { type: 'WINDOW_BLUR', metadata: { source: 'integration' } },
      { type: 'TAB_HIDDEN', metadata: { visibilityState: 'hidden' } },
      { type: 'FULLSCREEN_EXIT' },
    ],
  });
  assert(integrity.status === 200 && integrity.body.counted >= 2, 'integrity events recorded and counted by policy');

  const submit = await student.post(`/api/attempts/${attemptId}/submit`, { confirmUnanswered: true });
  assert(submit.status === 200, 'attempt submitted');

  const resume = await student.patch(
    `/api/attempts/${attemptId}/answers`,
    { updates: [{ questionId: questions[39].id, response: { value: 'late' } }] },
    { expectStatuses: [409, 400, 403] },
  );
  assert(resume.status >= 400, 'answers cannot be changed after submission');

  const result = await student.get(`/api/attempts/${attemptId}/result`);
  assert(result.body.rawScore === 30, `server-marked raw score is 30 (received ${result.body.rawScore})`);
  const session = result.body.sessions[0];
  assert(session.bandAvailable === true && session.band === 7, `estimated band is 7.0 (received ${session.band})`);
  assert(result.body.release.scoreAvailable === true, 'IMMEDIATE visibility released the score');
  assert(
    typeof result.body.bandNote === 'string' && result.body.bandNote.toLowerCase().includes('estimated'),
    'result labels the band as an estimate',
  );
  assert(result.body.integrity.counted >= 2, 'integrity summary is attached to the result');

  // Attempt limits: the assignment allows two attempts, the third must fail.
  const second = await student.post('/api/attempts', { assignmentId });
  assert(second.status === 201, 'a second attempt is allowed by maxAttempts');
  await student.post(`/api/attempts/${second.body.attemptId}/submit`, { confirmUnanswered: true });
  const third = await student.post('/api/attempts', { assignmentId }, { expectStatuses: [409, 403, 400] });
  assert(third.status >= 400, 'the third attempt is refused by the attempt limit');

  const history = await student.get('/api/student/attempts');
  assert(history.body.attempts.length >= 2, 'attempt history lists the attempts');

  // Self-service practice must not silently gain exam monitoring.
  const practice = await student.post('/api/attempts', { testId, mode: 'STRICT_EXAM' });
  const practiceState = await student.get(`/api/attempts/${practice.body.attemptId}`);
  assert(
    practiceState.body.integrity.policy.mode === 'PRACTICE',
    'students cannot self-select an exam integrity mode',
  );
  await student.post(`/api/attempts/${practice.body.attemptId}/submit`, { confirmUnanswered: true });

  return { attemptId };
}

async function fullMockFlow(admin, student, { versionId, writingVersionId }) {
  section('Flow 4 — FULL MOCK: multi-component sequence, section advance, submission');

  const created = await admin.post('/api/admin/tests', {
    title: `Integration Full Mock ${RUN}`,
    type: 'FULL_MOCK',
    summary: 'Two-component fixture created by the acceptance script.',
    contentOrigin: 'ORIGINAL',
  });
  const mock = await admin.put(`/api/admin/versions/${created.body.versionId}/content`, {
    sections: [],
    durationSeconds: 3600,
    isCompleteTest: true,
    mockComponents: [
      { skill: 'READING', testVersionId: versionId, label: 'Reading', durationSeconds: 1800, breakAfterSeconds: 30 },
      { skill: 'WRITING', testVersionId: writingVersionId, label: 'Writing', durationSeconds: 1800, breakAfterSeconds: 0 },
    ],
  });
  assert(mock.status === 200, 'full-mock version saved with two components');
  assert(mock.body.validation.publishable === true, 'full mock passes validation');

  await admin.post(`/api/admin/versions/${created.body.versionId}/publish`, {});

  const started = await student.post('/api/attempts', { testId: created.body.testId });
  assert(started.status === 201 && started.body.attemptId, 'full-mock attempt started');
  const attemptId = started.body.attemptId;

  let state = await student.get(`/api/attempts/${attemptId}`);
  assert(state.body.components.length === 2, 'both mock components are scheduled');
  assert(state.body.components[0].skill === 'READING', 'first component follows the configured sequence');
  assert(state.body.components[1].skill === 'WRITING', 'second component follows the configured sequence');
  assert(state.body.integrity.policy.mode === 'PRACTICE', 'self-service mock runs with the practice policy');
  assert(typeof state.body.integrity.notice === 'string' && state.body.integrity.notice.length > 0, 'integrity notice is configuration-driven');

  const firstQuestions = state.body.content.sections[0].groups.flatMap((group) => group.questions);
  await student.patch(`/api/attempts/${attemptId}/answers`, {
    updates: firstQuestions.slice(0, 5).map((question) => ({ questionId: question.id, response: { value: 'TRUE' } })),
  });

  const advanced = await student.post(`/api/attempts/${attemptId}/advance`, {});
  assert(advanced.status === 200 && advanced.body.activeComponentIndex === 1, 'candidate advanced to the second component');
  assert(advanced.body.submitted === false, 'advancing does not submit the whole attempt');

  state = await student.get(`/api/attempts/${attemptId}`);
  assert(state.body.components[state.body.activeComponentIndex].skill === 'WRITING', 'writing component is active now');

  const writingQuestion = state.body.content.sections[0].groups.flatMap((group) => group.questions)[0];
  const writingSaved = await student.post(`/api/attempts/${attemptId}/writing`, {
    questionId: writingQuestion.id,
    text: 'Integration fixture response. '.repeat(70),
  });
  assert(writingSaved.status === 200 && writingSaved.body.wordCount > 100, 'writing response saved with a server word count');

  const submitted = await student.post(`/api/attempts/${attemptId}/submit`, { confirmUnanswered: true });
  assert(submitted.status === 200, 'full-mock attempt submitted');

  const result = await student.get(`/api/attempts/${attemptId}/result`);
  assert(result.body.sessions.length === 2, 'result covers both skill sessions');
  const writingSession = result.body.sessions.find((session) => session.skill === 'WRITING');
  assert(writingSession.writing.length === 1, 'writing submission is attached to the result');
  assert(writingSession.writing[0].score === null, 'writing is left unmarked for a human, never auto-scored');
  assert(writingSession.writing[0].submissionId, 'writing submission id is exposed for teacher marking');

  return { attemptId, writingVersionId };
}

async function teacherMarkingFlow(teacher, admin, { attemptId }) {
  section('Flow 5 — TEACHER/ADMIN: marking writing and reading the attempt');

  const view = await admin.get(`/api/admin/attempts/${attemptId}`);
  const writing = view.body.sessions.flatMap((session) => session.writing)[0];
  assert(writing?.submissionId, 'admin attempt view exposes the writing submission id');

  const scored = await admin.post('/api/admin/writing-scores', {
    writingSubmissionId: writing.submissionId,
    band: 6.5,
    feedback: 'Clear structure; work on cohesion and range of vocabulary.',
  });
  assert(scored.status === 200, 'admin saved a human writing score');

  const after = await admin.get(`/api/admin/attempts/${attemptId}`);
  const rescored = after.body.sessions.flatMap((session) => session.writing)[0];
  assert(rescored.score?.band === 6.5, 'the saved band appears on the attempt');
  assert(rescored.score?.source === 'ADMIN', 'the score records its source');

  const audit = await admin.get('/api/admin/audit-logs?limit=50');
  const actions = audit.body.logs.map((entry) => entry.action);
  assert(actions.includes('WRITING_SCORE_SET'), 'administrative actions are written to the audit log');
  assert(actions.includes('VERSION_PUBLISH'), 'publishing is audited');
  assert(!JSON.stringify(audit.body).includes(PASSWORD), 'audit log never contains passwords');

  const settings = await admin.get('/api/admin/settings');
  assert(typeof settings.body.settings === 'object', 'platform settings are readable');
  await admin.patch('/api/admin/settings', { settings: { integrity_notice: `Integration notice ${RUN}` } });
  const reopened = await admin.get(`/api/admin/attempts/${attemptId}`);
  assert(reopened.status === 200, 'settings update does not break attempt reads');
}

async function main() {
  console.log(`IELTS platform acceptance run ${RUN}`);
  console.log(`Target: ${BASE_URL}`);

  const health = await fetch(`${BASE_URL}/api/health`);
  if (!health.ok) throw new Error(`Worker is not responding at ${BASE_URL}. Start it with "npm run dev".`);
  const healthBody = await health.json();
  assert(healthBody.ok === true, `worker health check (${healthBody.environment})`);

  const admin = createClient('admin');
  const status = await admin.get('/api/auth/status');

  // CSRF defence-in-depth: a foreign Origin must be rejected before any auth work.
  const crossOrigin = await fetch(`${BASE_URL}/api/auth/login`, {
    method: 'POST',
    headers: { 'content-type': 'application/json', origin: 'https://evil.example.test' },
    body: JSON.stringify({ email: 'nobody@example.test', password: PASSWORD }),
  });
  assert(crossOrigin.status === 403, 'cross-origin state-changing request is rejected (403)');

  if (process.env.ADMIN_EMAIL) {
    await admin.login(process.env.ADMIN_EMAIL);
  } else if (status.body.adminConfigured) {
    throw new Error(
      'An administrator already exists. Re-run with ADMIN_EMAIL=... ADMIN_PASSWORD=... to use that account, or point the script at a fresh local database.',
    );
  } else {
    const user = await admin.register(`admin-${RUN}@example.test`, 'Integration Admin', true);
    assert(user?.role === 'ADMIN', 'first registration bootstrapped the administrator account');
  }

  const studentEmail = `student-${RUN}@example.test`;
  await admin.post('/api/admin/users', {
    email: studentEmail,
    displayName: 'Integration Student',
    role: 'STUDENT',
    password: PASSWORD,
  });
  const teacherEmail = `teacher-${RUN}@example.test`;
  await admin.post('/api/admin/users', {
    email: teacherEmail,
    displayName: 'Integration Teacher',
    role: 'TEACHER',
    password: PASSWORD,
  });

  const teacher = createClient('teacher');
  await teacher.login(teacherEmail);
  const student = createClient('student');
  await student.login(studentEmail);
  assert(true, 'admin, teacher and student sessions established');

  const adminResult = await adminFlow(admin);
  const teacherResult = await teacherFlow(admin, teacher, studentEmail);
  const assignmentId = await assignmentFlow(teacher, {
    classroomId: teacherResult.classroomId,
    versionId: adminResult.versionId,
  });
  await studentFlow(student, { assignmentId, responses: adminResult.responses, testId: adminResult.testId });
  const mock = await fullMockFlow(admin, student, adminResult);
  await teacherMarkingFlow(teacher, admin, mock);

  const classroomReport = await teacher.get(`/api/teacher/assignments/${assignmentId}`);
  assert(classroomReport.body.report.some((row) => row.attemptsUsed >= 1), 'teacher report reflects the student attempts');
  const analytics = await teacher.get(`/api/teacher/classrooms/${teacherResult.classroomId}/analytics`);
  assert(analytics.body.skillPerformance.length >= 1, 'classroom analytics aggregates marked sessions');

  console.log(`\n${passed} checks passed, ${failed} failed.`);
  if (failed > 0) {
    console.error('\nFailures:');
    for (const failure of failures) console.error(` - ${failure}`);
    process.exitCode = 1;
  }
}

main().catch((error) => {
  console.error(`\nAcceptance run aborted: ${error.message}`);
  process.exitCode = 1;
});
